# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-tutorial',
                'doc_host': 'https://ankurdivekar.github.io',
                'git_url': 'https://github.com/ankurdivekar/nbdev-tutorial',
                'lib_path': 'nbdev_tutorial'},
  'syms': { 'nbdev_tutorial.core': {'nbdev_tutorial.core.foo': ('intro.html#foo', 'nbdev_tutorial/core.py')},
            'nbdev_tutorial.introduction': { 'nbdev_tutorial.introduction.foo': ( 'introduction.html#foo',
                                                                                  'nbdev_tutorial/introduction.py')}}}
